#!/bin/bash

[ ! -d ITK ] && git clone git://itk.org/ITK.git
cd ITK
sed -e "s|#![ ]*/usr/bin/python$|#!/usr/bin/python2|" \
      -e "s|#![ ]*/usr/bin/env python$|#!/usr/bin/env python2|" \
      -e "s|#![ ]*/bin/env python$|#!/usr/bin/env python2|" \
      -i $(find . -name '*.py')

rm -rf build
mkdir -p build
cd build
cmake .. -DBUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF \
	-DITK_USE_64BITS_IDS=ON -DITK_WRAP_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python2 \
	-DModule_ITKVtkGlue=ON -DModule_ITKDCMTK=ON -DModule_ITKIODCMTK=ON \
	-DITK_USE_SYSTEM_DCMTK=OFF -DITK_USE_SYSTEM_EXPAT=ON \
	-DITK_USE_SYSTEM_FFTW=ON -DITK_USE_SYSTEM_HDF5=ON -DITK_USE_SYSTEM_JPEG=ON \
	-DITK_USE_SYSTEM_PNG=ON -DITK_USE_SYSTEM_SZIP=ON -DITK_USE_SYSTEM_TIFF=ON \
	-DITK_USE_SYSTEM_ZLIB=ON && \

make -j8 && \
sudo make install
